urls.py
# -*- coding:utf-8 -*-
from django.contrib import admin
from django.conf.urls.defaults import patterns, include, url
from haystack.views import search_view_factory
from haystack.forms import SearchForm
from coop_local.views import ModelSearchView, SiteModelSearchView
from coop.forms import SiteSearchForm
from django.contrib.sites.models import Site

from coop_local.models import GenericDate
# # https://code.djangoproject.com/ticket/10405#comment:11
# from django.db.models.loading import cache as model_cache
# if not model_cache.loaded:
#     model_cache.get_models()

admin.autodiscover()

# Add you own URLs here
urlpatterns = []

urlpatterns += patterns('',
    url(r'^$', 'coop_local.views.home', name="home"),
    url(r'^inscription-mailing/$', 'coop_local.views.inscription_mailing', name="inscription_mailing"),
    url(r'^ressources/$', 'coop_local.search.views.search_resources_form', name="ressources"),
    url(r'^rubrique/ressources/$', 'coop_local.search.views.search_resources_form', name="ressources"),
    url(r'^search/ressources/$', 'coop_local.search.views.search_resources_results', name="ressources_results"),

    url(r'^financements/$', 'coop_local.views.grants_list', name="grants_list"),
    url(r'^financement/(?P<slug>[\w-]+)/$', 'coop_local.views.grant_detail', name="grant_detail"),

    url(r'^annonces/$', 'coop_local.views.annonces_list', name="annonces_list"),
    url(r'^annonces/(?P<slug>[\w-]+)/$', 'coop_local.views.annonces_category', name="annonces_category"),
    url(r'^annonce/(?P<slug>[\w-]+)/$', 'coop_local.views.annonce_detail', name="annonce_detail"),

    url(r'^contacts/$', 'coop_local.views.contacts', name="contacts"),
    url(r'^agenda/?$', 'coop_local.views.agenda_global', {}, name="agenda_liste"),
    url(r'^agenda/auvergne/?$', 'coop_local.views.agenda_global', {'filter':'Auvergne'}, name="agenda_auvergne"),
    url(r'^agenda/cerapcoop/?$', 'coop_local.views.agenda_global', {'filter':'Cerapcoop'}, name="agenda_cerapcoop"),
    url(r'^agenda/proposer/$', 'coop_local.views.add_event', {}, name="add_event"),
    url(r'^formations/?$', 'coop_local.views.agenda_global', {'filter': 'Formation'}, name="agenda_formation"),
    url(r'^plan-du-site/$', 'coop_local.views.plan', name="plan-du-site"),
    url(r'^tag/(?P<slug>[\w-]+)/((?P<param>.+)/)?$', 'coop_local.views.tag_detail', name="tag_detail"),

    # url(r'^agenda/?$', 'coop.agenda.views.month_view', {'queryset': GenericDate.objects.all(), 'articles':True }, name='agenda-default'),

    # url(r'^discipline/(?P<slug>[\w-]+)/$', 'coop_local.views.discipline_detail', name="discipline_detail"),

#    	url(r'^org/$', 'coop_local.views.org_list', name="org_list"), #view coop
)

urlpatterns += patterns('haystack.views',
        url(r'^search/search/$', search_view_factory(
            view_class=SiteModelSearchView,
            form_class=SiteSearchForm,
            site=Site.objects.get_current(),
            template='search/search.html',
            load_all=False
        ), name='haystack_search'),
    )

urlpatterns += patterns('haystack.views',
        url(r'^search/searchcerapcoop/$', search_view_factory(
            view_class=SiteModelSearchView,
            form_class=SiteSearchForm,
            site=Site.objects.get(id=1),
            template='search/search.html',
            load_all=False
        ), name='haystack_search'),
    )

urlpatterns += patterns('haystack.views',
        url(r'^search/searchall/$', search_view_factory(
            view_class=ModelSearchView,
            form_class=SearchForm,
            template='search/search.html',
            load_all=False
        ), name='haystack_search'),
)

from coop.default_project_urls import urlpatterns as default_project_urls
urlpatterns += default_project_urls

forms.py
# -*- coding:utf-8 -*-

from django.forms import ModelForm
from coop_local.models import Annonce
from django import forms
from datetimewidget.widgets import DateTimeWidget


class MLForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    email = forms.EmailField(label='email', widget=forms.TextInput(attrs={'placeholder': u'indiquez votre e-mail'}))
    first_name = forms.CharField(max_length=100, label='Prénom', required=True, 
                                widget=forms.TextInput(attrs={'placeholder': u'votre prénom'}))
    name = forms.CharField(max_length=100, label='Nom', required=True,
                            widget=forms.TextInput(attrs={'placeholder': u'votre nom'}))
    structure = forms.CharField(max_length=100, label='Structure', required=False,
                            widget=forms.TextInput(attrs={'placeholder': u'votre structure (optionnel)'}))

    adresse = forms.CharField(max_length=100, label='Adresse', required=False,
                            widget=forms.TextInput(attrs={'placeholder': u'adresse'}))
    code_postal = forms.CharField(max_length=5, label='Code postal', required=False,
                            widget=forms.TextInput(attrs={'placeholder': u'code postal'}))
    ville = forms.CharField(max_length=100, label='Commune', required=False,
                            widget=forms.TextInput(attrs={'placeholder': u'ville'}))



class AnnonceForm(ModelForm):
    class Meta:
        model = Annonce
        fields = ['label', 'description','annonce_category','web','expiration',
        'remote_person_label', 'tel', 'email', 'remote_organization_label']
        labels = {
            'remote_organization_label': 'Votre structure',
            'remote_person_label': 'Nom du contact'
        }
        dt_options = {'pickerPosition': 'top-right', 'weekStart' : 1 , 'minuteStep': 15 , 
        'format': 'dd/mm/yyyy', 'minView': 1}

        widgets = {
                #Use localization
                'expiration': DateTimeWidget(options= dt_options, attrs={'id':"expiration"}, usel10n = True)
            }
        # exclude = ['active','sites','slug','organization','remote_organization_uri',
        # 'tags','person','remote_person_uri', 'maj']
        # widgets = autocomplete_light.get_widgets_dict(Produit, Fournisseur)


class ReponseAnnonce(forms.Form):
    sender = forms.EmailField(label='Votre e-mail')
    message = forms.CharField(widget=forms.Textarea, label='Votre message')


class PostAgenda(forms.Form):
    dt_options = {'pickerPosition': 'top-right', 'weekStart' : 1 , 'minuteStep': 15, 
        'format': 'yyyy-mm-dd hh:ii', 'minView': 0}
    author = forms.CharField(label='Nom et prénom')
    org = forms.CharField(label='Organisme')
    titre = forms.CharField(label=u"Titre de l'événement")
    description = forms.CharField(widget=forms.Textarea, label=u"Description de l'événement")
    logo = forms.ImageField(required=False, label=u"Logo / Illustration")
    link = forms.URLField(label='Lien web', required=False)
    desc_link = forms.CharField(label='Intitulé du lien', required=False)
    dt_start = forms.DateTimeField( label="Date/heure début",
                                    widget=DateTimeWidget(options=dt_options, 
                                                attrs={'id':"dt_start"}, usel10n = True) 
                                    )
    dt_end = forms.DateTimeField(   label="Date/heure fin",
                                    widget=DateTimeWidget(options= dt_options, 
                                            attrs={'id':"dt_end"}, usel10n = True)
                                    )

templates/ajax/mailing_form.html
{% load ml_form %}

{% if msg %}<p class="mailing_form_msg">{{ msg }}</p>{% endif %}

{% if  not mailing_form %}{% ml_form as mailing_form%}{% endif %}

          <form id="mailing_form" action="/inscription-mailing/" method="post">
            {% csrf_token %}
            {{ mailing_form.as_p }}
            <input type="submit" class="btn btn-small btn-success" value="Valider l'inscription"><br>
            <span class="disclaimer">Nous ne revendons pas vos coordonnées.</span>
          </form>

<script type="text/javascript">

$(function(){


  $('#mailing_form #id_adresse').parent('p:not(.error)').addClass('visuallyhidden');
  $('#mailing_form #id_code_postal').parent('p:not(.error)').addClass('visuallyhidden');
  $('#mailing_form #id_ville').parent('p:not(.error)').addClass('visuallyhidden');
  {% if not mailing_form.errors %}
  $('#mailing_form #id_first_name').parent('p:not(.error)').addClass('visuallyhidden');
  $('#mailing_form #id_name').parent('p:not(.error)').addClass('visuallyhidden');
  $('#mailing_form #id_structure').parent('p:not(.error)').addClass('visuallyhidden');
  $('#mailing_form .btn').addClass('visuallyhidden');
  $('#mailing_form .disclaimer').addClass('visuallyhidden');{% endif %}

  $('#mailing_form #id_email').focus(function(){
        $('#mailing_form').css('width','100%');
        $('#mailing_form #id_first_name').parent('p').removeClass('visuallyhidden');
        $('#mailing_form #id_name').parent('p').removeClass('visuallyhidden');
        $('#mailing_form #id_structure').parent('p').removeClass('visuallyhidden');
        $('#mailing_form .btn').removeClass('visuallyhidden');
        $('#mailing_form .disclaimer').removeClass('visuallyhidden')
    });
  $('#mailing_form #id_structure').focus(function(){
        $('#mailing_form #id_adresse').parent('p').removeClass('visuallyhidden');
        $('#mailing_form #id_code_postal').parent('p').removeClass('visuallyhidden');
        $('#mailing_form #id_ville').parent('p').removeClass('visuallyhidden');
    });



  $('#mailing_form').on('submit', function(e){
           form = $(this);
             $.ajax({
                 type: 'POST',
                 dataType : 'html',
                 url: form.attr("action"),
                 data: form.serialize(),
                 success: function(data){ $('#mailing_form_inner').html(data) }
             });
             e.preventDefault();
             e.stopPropagation();
    });


	
})


</script>